services:
  postgres-decidim:
    image: postgres:15.3
    container_name: postgres-decidim
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-decidim_data:/var/lib/postgresql/data

volumes:
  postgres-decidim_data: